### ISSUE TITLE
Dependency resolution exceptions are caught and logged incorrectly

### ISSUE THREAD

**Issue by willferguson** [vert-x3/vertx-maven-service-factory#13]
When deploying a verticle with maven, if the system can't resolve one of your dependencies, you will get an error stating `Cannot find module X in maven repositories`, where X is the module you're trying to deploy, not the dependency it can't find. This makes debugging dependency resolution problems a little tricky!

See MavenVerticleFactory:173

>> catch (DependencyResolutionException e) {
>>      throw new IllegalArgumentException("Cannot find module " + coordsString + " in maven repositories");

**Comment by cescoffier** [comment]
You are right, the error message should be improved.

**Comment by cescoffier** [comment]
Fixed in master.
