### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by Xophe** [vert-x3/vertx-maven-service-factory#22]
The docs says :

> The service name (my-service) can be omitted when the META-INF/MANIFEST a the jar containing
> the service contains a Main-Verticle entry that declares the verticle to run:
> 
> vertx.deployVerticle("maven:com.mycompany:my-artifact:1.2::my-service", options);
> And the manifest contains:
> Main-Verticle: service:my.service

It should say :

> The service name (my-service) can be omitted when the META-INF/MANIFEST **in** the jar containing
> the service contains a Main-Verticle entry that declares the verticle to run:
> 
> vertx.deployVerticle("**maven:com.mycompany:my-artifact:1.2**", options);
> and the manifest contains:
> Main-Verticle: service:**my-service**
> and the jar contains a my-service.json file.

I had to read the code to get it right. Works nicely one this clarified.

**Comment by cescoffier** [comment]
The fix should be soon available on the web site. Thanks for reporting the error !

**Comment by Xophe** [comment]
You're welcome. Except this little thing, it works great and is exactly 
what I need.
Regards.
